let skillCount=10,projectCount=10;
const $=s=>document.querySelector(s);
function renderSkills(){const g=$('#skillsGrid');g.innerHTML=skills.slice(0,skillCount).map(([n,p])=>`<div class="skill glass"><div><b>${n}</b><span>${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`).join('');}
function renderProjects(){const g=$('#projectGrid');g.innerHTML=projects.slice(0,projectCount).map((p,i)=>`<article class="project glass" data-i="${i}"><img loading="lazy" src="${p.img}" alt="${p.name}"><div><small>${p.placeholder?'CONCEPT PLACEHOLDER':'VERIFIED REPOSITORY'}</small><h3>${p.name}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></article>`).join('');document.querySelectorAll('.project').forEach(x=>x.onclick=()=>openProject(+x.dataset.i));}
$('#skillMore').onclick=()=>{skillCount=skillCount===10?15:10;renderSkills();$('#skillMore').innerHTML=skillCount===10?'Show More 10 ＋':'Show Less −';};
$('#projectMore').onclick=()=>{projectCount=projectCount<projects.length?Math.min(projectCount+10,projects.length):10;renderProjects();$('#projectMore').innerHTML=projectCount===10?'Show More 10 ＋':projectCount>=projects.length?'Show Less −':'Show More 10 ＋';};
function openProject(i){const p=projects[i];$('#modalImg').src=p.img;$('#modalImg').alt=p.name;$('#modalTitle').textContent=p.name;$('#modalDesc').textContent=p.desc;$('#modalStatus').textContent=p.placeholder?'CONCEPT PLACEHOLDER':'VERIFIED REPOSITORY';$('#modalTags').innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('');$('#modalLink').href=p.url;$('#modalLink').style.display=p.url==='#'?'none':'inline-flex';$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.classList.add('locked');}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.classList.remove('locked');}
$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.onkeydown=e=>{if(e.key==='Escape')closeModal()};
$('#menuBtn').onclick=()=>{$('#navLinks').classList.toggle('open')};document.querySelectorAll('.links a').forEach(a=>a.onclick=()=>$('#navLinks').classList.remove('open'));
const sections=[...document.querySelectorAll('section[data-section],section[id]')],nav=[...document.querySelectorAll('.links a')];const observer=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));}})},{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>observer.observe(s));
$('#contactForm').onsubmit=e=>{e.preventDefault();const n=$('#name').value.trim(),em=$('#email').value.trim(),m=$('#message').value.trim();if(!n||!em||!m||!$('#email').checkValidity()){$('#status').textContent='Please enter a valid name, email and message.';return}$('#status').textContent='Message validated successfully. Connect your email service to receive submissions.';e.target.reset();};
renderSkills();renderProjects();