/* Skills and proficiency — ordered exactly as provided */
const skills=[
['HTML',96],
['CSS',93],
['JavaScript',90],
['TypeScript',85],
['Python',87],
['Prompt Engineering',94],
['N8N',86],
['Zapier',88],
['Modern Python Web Dev',84],
['Web Development',92],
['API Integration',90],
['AI Chatbot Development',89],
['Full Stack Development',86],
['Backend Development',85],
['Frontend Development',90],
['Next.js',90],
['Git',90],
['Workflows',90],
['AI Developer',90],
['Problem Solving',90],
['GitHub Deployment',90],
['Streamlit',88],
['FastAPI',84],
['Node.js',82],
['Tailwind CSS',85],
['Firebase',80],
['REST APIs',88],
['GitHub Actions',82],
['AI Agents',86],
['UI/UX',82],
];